
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackbaremetalset
  failurePolicy: Fail
  name: mopenstackbaremetalset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackbaremetalsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackclient
  failurePolicy: Fail
  name: mopenstackclient.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackconfiggenerator
  failurePolicy: Fail
  name: mopenstackconfiggenerator.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackconfiggenerators
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: mopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackdeploy
  failurePolicy: Fail
  name: mopenstackdeploy.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackdeploys
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackephemeralheat
  failurePolicy: Fail
  name: mopenstackephemeralheat.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackephemeralheats
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackipset
  failurePolicy: Fail
  name: mopenstackipset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackipsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstacknet
  failurePolicy: Fail
  name: mopenstacknet.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstacknetattachment
  failurePolicy: Fail
  name: mopenstacknetattachment.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetattachments
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstacknetconfig
  failurePolicy: Fail
  name: mopenstacknetconfig.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackprovisionserver
  failurePolicy: Fail
  name: mopenstackprovisionserver.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackprovisionservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstackvmset
  failurePolicy: Fail
  name: mopenstackvmset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackvmsets
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackbackup
  failurePolicy: Fail
  name: vopenstackbackup.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackbackups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackbackuprequest
  failurePolicy: Fail
  name: vopenstackbackuprequest.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackbackuprequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackbaremetalset
  failurePolicy: Fail
  name: vopenstackbaremetalset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openstackbaremetalsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackclient
  failurePolicy: Fail
  name: vopenstackclient.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openstackclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: vopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openstackcontrolplanes
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackipset
  failurePolicy: Fail
  name: vopenstackipset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackipsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstacknet
  failurePolicy: Fail
  name: vopenstacknet.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openstacknets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstacknetattachment
  failurePolicy: Fail
  name: vopenstacknetattachment.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetattachments
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstacknetconfig
  failurePolicy: Fail
  name: vopenstacknetconfig.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknetconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackprovisionserver
  failurePolicy: Fail
  name: vopenstackprovisionserver.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openstackprovisionservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackvmset
  failurePolicy: Fail
  name: vopenstackvmset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - openstackvmsets
  sideEffects: None
