
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-osp-director-openstack-org-v1beta1-openstacknet
  failurePolicy: Fail
  name: mopenstacknet.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstacknets

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackbaremetalset
  failurePolicy: Fail
  name: vopenstackbaremetalset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackbaremetalsets
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackcontrolplane
  failurePolicy: Fail
  name: vopenstackcontrolplane.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackcontrolplanes
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-osp-director-openstack-org-v1beta1-openstackvmset
  failurePolicy: Fail
  name: vopenstackvmset.kb.io
  rules:
  - apiGroups:
    - osp-director.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackvmsets
