
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - create
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nmstate.io
  resources:
  - nodenetworkconfigurationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackuprequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackups/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbackups/status
  verbs:
  - get
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackclients
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackclients/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfiggenerators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackconfigversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackcontrolplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackdeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackdeploys/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackdeploys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackephemeralheats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackephemeralheats/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackephemeralheats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackipsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackipsets/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackipsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackmacaddresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackmacaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackmacaddresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetattachments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetattachments/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetattachments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetconfigs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetconfigs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknetconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknets/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstacknets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackplaybookgenerators
  verbs:
  - delete
  - deletecollection
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets/finalizers
  verbs:
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackvmsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworknodepolicies
  - sriovnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovnetwork.openshift.io
  resources:
  - sriovnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: openstack
rules:
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - hco.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - template.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
