# Note: when bundle gets created there is a prefix 'osp-director-operator'
# being added to the ServiceAccount names
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstackclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstackclient-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstackclient-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstackclient-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: osp-director-operator-openstackclient
  namespace: openstack
- kind: ServiceAccount
  name: openstackclient
  namespace: openstack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstackprovisionserver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstackprovisionserver-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers
  verbs:
  - get
  - list
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackprovisionservers/status
  verbs:
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstackprovisionserver-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstackprovisionserver-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: osp-director-operator-openstackprovisionserver
  namespace: openstack
- kind: ServiceAccount
  name: openstackprovisionserver
  namespace: openstack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstackplaybookgenerator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstackplaybookgenerator-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstackplaybookgenerator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstackplaybookgenerator-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: osp-director-operator-openstackplaybookgenerator
  namespace: openstack
- kind: ServiceAccount
  name: openstackplaybookgenerator
  namespace: openstack