apiVersion: osp-director.openstack.org/v1beta1
kind: ControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  controller:
    controllerCount: 1
    cores: 2
    memory: 5
    diskSize: 10
    baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
    storageClass: host-nfs-storageclass
    networks:
    - name: ctlplane
