apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackNet
metadata:
  name: ctlplane
spec:
  cidr: 192.168.0.0/24
  allocationStart: 192.168.0.4
  allocationEnd: 192.168.0.250
  gateway: 192.168.0.1 #optional
