apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackVMSet
metadata:
  name: customvmset
  namespace: openstack
spec:
  vmCount: 1
  cores: 2
  memory: 20
  diskSize: 50
  baseImageVolumeName: openstack-base-img
  storageClass: host-nfs-storageclass
  #imageImportStorageClass: local #optional
  deploymentSSHSecret: osp-controlplane-ssh-keys
  isTripleoRole: true
  ctlplaneInterface: enp2s0 #defaults to enp2s0
  networks:
    - ctlplane
  roleName: SomeCustomRole
