apiVersion: osp-director.openstack.org/v1beta1
kind: ControllerVM
metadata:
  name: osp-controller
  namespace: openstack
spec:
  baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
  controllerCount: 1
  cores: 2
  memory: 5
  diskSize: 10
  storageClass: host-nfs-storageclass
  deploymentSSHSecret: osp-controlplane-ssh-keys
  ospNetwork:
    bridgeName: br-osp
    name: osp
    desiredState:
      interfaces:
      - name: br-osp # must be same as bridgeName
        description: Linux bridge with enp6s0 as a port
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: false
          port:
          - name: enp6s0
  networks:
    - ctlplane
  role: controller
