
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: openstackcontrolplanes.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: OpenStackControlPlane
    listKind: OpenStackControlPlaneList
    plural: openstackcontrolplanes
    shortNames:
    - osctlplane
    - osctlplanes
    singular: openstackcontrolplane
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackControlPlane represents a virtualized OpenStack control
          plane configuration
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackControlPlaneSpec defines the desired state of OpenStackControlPlane
            properties:
              gitSecret:
                description: GitSecret used to pull playbooks into the openstackclient
                  pod
                type: string
              openStackClientImageURL:
                description: OpenstackClient image
                type: string
              openStackClientNetworks:
                default:
                - ctlplane
                - external
                description: OpenStackClientNetworks the name(s) of the OpenStackClientNetworks
                  used to attach the openstackclient to
                items:
                  type: string
                type: array
              openStackClientStorageClass:
                description: OpenStackClientStorageClass storage class
                type: string
              passwordSecret:
                description: PasswordSecret used to e.g specify root pwd
                type: string
              virtualMachineRoles:
                additionalProperties:
                  description: OpenStackVirtualMachineRoleSpec - defines the desired
                    state of VMs
                  properties:
                    baseImageURL:
                      description: Name of the VM base image used to setup the VM
                      type: string
                    baseImageVolumeName:
                      description: BaseImageVolumeName Optional. If supplied will
                        be used as the base volume for the VM instead of BaseImageURL.
                      type: string
                    cores:
                      description: number of Cores assigned to the VM
                      format: int32
                      type: integer
                    ctlplaneInterface:
                      default: enp2s0
                      description: Interface to use for ctlplane network
                      type: string
                    diskSize:
                      description: root Disc size in GB
                      format: int32
                      type: integer
                    isTripleoRole:
                      default: true
                      description: in case of external functionality, like 3rd party
                        network controllers, set to false to ignore role in rendered
                        overcloud templates.
                      type: boolean
                    memory:
                      description: amount of Memory in GB used by the VM
                      format: int32
                      type: integer
                    networks:
                      default:
                      - ctlplane
                      - external
                      - internalapi
                      - tenant
                      - storage
                      - storagemgmt
                      description: Networks the name(s) of the OpenStackNetworks used
                        to generate IPs
                      items:
                        type: string
                      type: array
                    roleCount:
                      description: Number of VMs for the role
                      type: integer
                    roleName:
                      description: RoleName the name of the TripleO role this VM Spec
                        is associated with. If it is a TripleO role, the name must
                        match.
                      type: string
                    storageClass:
                      description: StorageClass to be used for the controller disks
                      type: string
                  required:
                  - cores
                  - ctlplaneInterface
                  - diskSize
                  - memory
                  - networks
                  - roleCount
                  - roleName
                  type: object
                description: List of VirtualMachine roles
                type: object
            required:
            - gitSecret
            - openStackClientImageURL
            - virtualMachineRoles
            type: object
          status:
            description: OpenStackControlPlaneStatus defines the observed state of
              OpenStackControlPlane
            properties:
              vipStatus:
                additionalProperties:
                  description: HostStatus represents the hostname and IP info for
                    a specific VM
                  properties:
                    hostname:
                      type: string
                    ipaddresses:
                      additionalProperties:
                        type: string
                      type: object
                  required:
                  - hostname
                  - ipaddresses
                  type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
