
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: openstacknetattachments.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: OpenStackNetAttachment
    listKind: OpenStackNetAttachmentList
    plural: openstacknetattachments
    shortNames:
    - osnetattachment
    - osnetsattachment
    - osnetatt
    - osnetsatt
    singular: openstacknetattachment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status
      jsonPath: .status.currentState
      name: Status
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackNetAttachment is the Schema for the openstacknetattachments
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackNetAttachmentSpec defines the desired state of OpenStackNetAttachment
            properties:
              attachConfiguration:
                description: AttachConfiguration used for NodeNetworkConfigurationPolicy
                  or NodeSriovConfigurationPolicy
                properties:
                  nodeNetworkConfigurationPolicy:
                    description: NodeNetworkConfigurationPolicySpec defines the desired
                      state of NodeNetworkConfigurationPolicy
                    properties:
                      desiredState:
                        description: The desired configuration of the policy
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      nodeSelector:
                        additionalProperties:
                          type: string
                        description: 'NodeSelector is a selector which must be true
                          for the policy to be applied to the node. Selector which
                          must match a node''s labels for the policy to be scheduled
                          on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/'
                        type: object
                    type: object
                  nodeSriovConfigurationPolicy:
                    description: NodeSriovConfigurationPolicy - Node selector and
                      desired state for SRIOV network
                    properties:
                      desiredState:
                        description: SriovState - SRIOV-specific configuration details
                          for an OSP network
                        properties:
                          deviceType:
                            default: vfio-pci
                            type: string
                          mtu:
                            default: 9000
                            format: int32
                            type: integer
                          numVfs:
                            format: int32
                            type: integer
                          port:
                            type: string
                          rootDevice:
                            type: string
                          spoofCheck:
                            default: "on"
                            enum:
                            - "on"
                            - "off"
                            type: string
                          trust:
                            default: "off"
                            enum:
                            - "on"
                            - "off"
                            type: string
                        required:
                        - numVfs
                        - port
                        type: object
                      nodeSelector:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                type: object
            required:
            - attachConfiguration
            type: object
          status:
            description: OpenStackNetAttachmentStatus defines the observed state of
              OpenStackNetAttachment
            properties:
              attachType:
                description: AttachType of the OpenStackNetAttachment
                type: string
              bridgeName:
                description: BridgeName of the OpenStackNetAttachment
                type: string
              conditions:
                description: 'TODO: It would be simpler, perhaps, to just have Conditions
                  and get rid of CurrentState, but we are using the same approach
                  in other CRDs for now anyhow Conditions - conditions to display
                  in the OpenShift GUI, which reflect CurrentState'
                items:
                  description: Condition - A particular overall condition of a certain
                    resource
                  properties:
                    lastHearbeatTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      description: ConditionReason - Why a particular condition is
                        true, false or unknown
                      type: string
                    status:
                      type: string
                    type:
                      description: ConditionType - A summarizing name for a given
                        condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              currentState:
                description: CurrentState - the overall state of the network attachment
                type: string
            required:
            - attachType
            - bridgeName
            - currentState
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
