
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: openstackconfigversions.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: OpenStackConfigVersion
    listKind: OpenStackConfigVersionList
    plural: openstackconfigversions
    shortNames:
    - osconfigversion
    - osconfigversions
    singular: openstackconfigversion
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Config Generator Name
      jsonPath: .spec.ConfigGeneratorName
      name: Generator
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackConfigVersion represents a set of executable Ansible
          playbooks
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackConfigVersionSpec defines the desired state of OpenStackConfigVersion
            properties:
              configGeneratorName:
                type: string
              ctlplaneExports:
                type: string
              diff:
                type: string
              hash:
                type: string
            required:
            - configGeneratorName
            - ctlplaneExports
            - diff
            - hash
            type: object
          status:
            description: OpenStackConfigVersionStatus defines the observed state of
              OpenStackConfigVersion
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
