
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: openstackipsets.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: OpenStackIPSet
    listKind: OpenStackIPSetList
    plural: openstackipsets
    shortNames:
    - osipset
    - osipsets
    singular: openstackipset
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackIPSet represents a group of IP addresses for a specific
          deployment role within the OpenStack Overcloud
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackIPSetSpec defines the desired state of OpenStackIPSet
            properties:
              addToPredictableIPs:
                description: AddToPredictableIPs add/ignore ipset to add entries to
                  Predictable IPs list
                type: boolean
              hostCount:
                description: HostCount Host count
                type: integer
              networks:
                description: Networks the name(s) of the OpenStackNetworks used to
                  generate IPs
                items:
                  type: string
                type: array
              roleName:
                description: RoleName the name of the TripleO role this VM Spec is
                  associated with. If it is a TripleO role, the name must match.
                type: string
              vip:
                description: VIP flag to indicate ipset is a request for a VIP
                type: boolean
            required:
            - addToPredictableIPs
            - hostCount
            - networks
            - roleName
            - vip
            type: object
          status:
            description: OpenStackIPSetStatus set of hosts with IP information
            properties:
              hosts:
                additionalProperties:
                  description: OpenStackIPHostsStatus per host IP set
                  properties:
                    ipaddresses:
                      additionalProperties:
                        type: string
                      type: object
                  required:
                  - ipaddresses
                  type: object
                type: object
              networks:
                additionalProperties:
                  description: OpenStackNetSpec defines the desired state of OpenStackNet
                  properties:
                    allocationEnd:
                      description: AllocationEnd a set of IPs that are reserved and
                        will not be assigned
                      type: string
                    allocationStart:
                      description: AllocationStart a set of IPs that are reserved
                        and will not be assigned
                      type: string
                    attachConfiguration:
                      description: AttachConfiguration used for NodeNetworkConfigurationPolicy
                        and NetworkAttachmentDefinition
                      properties:
                        bridgeName:
                          type: string
                        nodeNetworkConfigurationPolicy:
                          description: NodeNetworkConfigurationPolicySpec defines
                            the desired state of NodeNetworkConfigurationPolicy
                          properties:
                            desiredState:
                              description: The desired configuration of the policy
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            nodeSelector:
                              additionalProperties:
                                type: string
                              description: 'NodeSelector is a selector which must
                                be true for the policy to be applied to the node.
                                Selector which must match a node''s labels for the
                                policy to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/'
                              type: object
                          type: object
                      type: object
                    cidr:
                      description: Cidr the cidr to use for this network
                      type: string
                    gateway:
                      description: Gateway optional gateway for the network
                      type: string
                    vlan:
                      description: Vlan ID of the network
                      type: integer
                  required:
                  - allocationEnd
                  - allocationStart
                  - attachConfiguration
                  - cidr
                  type: object
                type: object
            required:
            - hosts
            - networks
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
