
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: baremetalsets.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: BaremetalSet
    listKind: BaremetalSetList
    plural: baremetalsets
    singular: baremetalset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BaremetalSet is the Schema for the baremetalsets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BaremetalSetSpec defines the desired state of BaremetalSet
          properties:
            deploymentSSHSecret:
              description: Name of secret holding the stack-admin ssh keys
              type: string
            mgmtCidr:
              description: CIDR for management network
              type: string
            mgmtInterface:
              description: Interface to use for management network
              type: string
            replicas:
              description: Replicas The number of baremetalhosts to attempt to aquire
              type: integer
            rhelImageUrl:
              description: 'Remote URL pointing to desired RHEL qcow2 image (TODO:
                currently gzipped only) for the set'
              type: string
          required:
          - deploymentSSHSecret
          - mgmtCidr
          - mgmtInterface
          - rhelImageUrl
          type: object
        status:
          description: BaremetalSetStatus defines the observed state of BaremetalSet
          properties:
            baremetalHosts:
              additionalProperties:
                description: BaremetalHost represents a BMH resource allocated by
                  the BaremetalSet
                properties:
                  mgmtIP:
                    type: string
                  secretName:
                    type: string
                required:
                - mgmtIP
                - secretName
                type: object
              type: object
          required:
          - baremetalHosts
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
