
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: openstackprovisionservers.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: OpenStackProvisionServer
    listKind: OpenStackProvisionServerList
    plural: openstackprovisionservers
    singular: openstackprovisionserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OpenStackProvisionServer is the Schema for the openstackprovisionservers
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OpenStackProvisionServerSpec defines the desired state of OpenStackProvisionServer
          properties:
            port:
              description: The port on which the Apache server should listen
              type: integer
            rhelImageUrl:
              description: 'URL to *gzipped* RHEL qcow2 image (TODO: support uncompressed
                -- current implementation is Metal3 pattern)'
              type: string
          required:
          - port
          - rhelImageUrl
          type: object
        status:
          description: OpenStackProvisionServerStatus defines the observed state of
            OpenStackProvisionServer
          properties:
            localImageUrl:
              description: URL of provisioning image on underlying Apache web server
              type: string
            provisionIp:
              description: IP of the provisioning interface on the node running the
                ProvisionServer pod
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
