
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: openstackbaremetalsets.osp-director.openstack.org
spec:
  group: osp-director.openstack.org
  names:
    kind: OpenStackBaremetalSet
    listKind: OpenStackBaremetalSetList
    plural: openstackbaremetalsets
    singular: openstackbaremetalset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OpenStackBaremetalSet represent a set of baremetal hosts for a
        specific role within the Overcloud deployment
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OpenStackBaremetalSetSpec defines the desired state of OpenStackBaremetalSet
          properties:
            baseImageUrl:
              description: Remote URL pointing to desired RHEL qcow2 image
              type: string
            bmhLabelSelector:
              additionalProperties:
                type: string
              description: BmhLabelSelector allows for a sub-selection of BaremetalHosts
                based on arbitrary labels
              type: object
            ctlplaneInterface:
              description: Interface to use for ctlplane network
              type: string
            deploymentSSHSecret:
              description: Name of secret holding the stack-admin ssh keys
              type: string
            hardwareReqs:
              description: Hardware requests for sub-selection of BaremetalHosts with
                certain hardware specs
              properties:
                cpuReqs:
                  description: CPUReqs defines specific CPU hardware requests
                  properties:
                    arch:
                      description: Arch is a scalar (string) because it wouldn't make
                        sense to give it an "exact-match" option Can be either "x86_64"
                        or "ppc64le" if included
                      enum:
                      - x86_64
                      - ppc64le
                      type: string
                    countReq:
                      description: CPUCountReq defines a specific hardware request
                        for CPU core count
                      properties:
                        count:
                          minimum: 1
                          type: integer
                        exactMatch:
                          description: If ExactMatch == false, actual count > Count
                            will match
                          type: boolean
                      type: object
                    mhzReq:
                      description: CPUMhzReq defines a specific hardware request for
                        CPU clock speed
                      properties:
                        exactMatch:
                          description: If ExactMatch == false, actual mhz > Mhz will
                            match
                          type: boolean
                        mhz:
                          minimum: 1
                          type: integer
                      type: object
                  type: object
                diskReqs:
                  description: DiskReqs defines specific disk hardware requests
                  properties:
                    gbReq:
                      description: DiskGbReq defines a specific hardware request for
                        disk size
                      properties:
                        exactMatch:
                          description: If ExactMatch == false, actual GB > Gb will
                            match
                          type: boolean
                        gb:
                          minimum: 1
                          type: integer
                      type: object
                    ssdReq:
                      description: SSD is scalar (bool) because it wouldn't make sense
                        to give it an "exact-match" option
                      properties:
                        exactMatch:
                          description: We only actually care about SSD flag if it
                            is true or ExactMatch is set to true. This second flag
                            is necessary as SSD's bool zero-value (false) is indistinguishable
                            from it being explicitly set to false
                          type: boolean
                        ssd:
                          type: boolean
                      type: object
                  type: object
                memReqs:
                  description: MemReqs defines specific memory hardware requests
                  properties:
                    gbReq:
                      description: MemGbReq defines a specific hardware request for
                        memory size
                      properties:
                        exactMatch:
                          description: If ExactMatch == false, actual GB > Gb will
                            match
                          type: boolean
                        gb:
                          minimum: 1
                          type: integer
                      type: object
                  type: object
              type: object
            networks:
              description: Networks the name(s) of the OpenStackNetworks used to generate
                IPs
              items:
                type: string
              type: array
            passwordSecret:
              description: 'PasswordSecret the name of the secret used to optionally
                set the root pwd by adding NodeRootPassword: <base64 enc pwd> to the
                secret data'
              type: string
            provisionServerName:
              description: ProvisionServerName Optional. If supplied will be used
                as the base Image for the baremetalset instead of baseImageURL.
              type: string
            replicas:
              description: Replicas The number of baremetalhosts to attempt to aquire
              minimum: 0
              type: integer
            role:
              description: Role the name of the Overcloud role this IPset is associated
                with. Used to generate hostnames.
              type: string
          required:
          - ctlplaneInterface
          - deploymentSSHSecret
          - networks
          - role
          type: object
        status:
          description: OpenStackBaremetalSetStatus defines the observed state of OpenStackBaremetalSet
          properties:
            baremetalHosts:
              additionalProperties:
                description: OpenStackBaremetalHostStatus represents the observed
                  state of a particular allocated BaremetalHost resource
                properties:
                  ctlplaneIP:
                    type: string
                  hostname:
                    type: string
                  networkDataSecretName:
                    type: string
                  online:
                    type: boolean
                  userDataSecretName:
                    type: string
                required:
                - ctlplaneIP
                - hostname
                - networkDataSecretName
                - online
                - userDataSecretName
                type: object
              type: object
          required:
          - baremetalHosts
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
