name: Golang lint, vet and unit test pipeline

on: [push, pull_request]

jobs:
  test:
    name: github (govet, golint and gotest)
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.x
      - name: Checkout project code
        uses: actions/checkout@v3
      - name: Run govet.sh
        run: make govet
      - name: Run golint.sh
        run: make golint
      - name: Run gotest.sh
        run: make gotest

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: skip branch check
      run: echo "SKIP=no-commit-to-branch" >> "$GITHUB_ENV"
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files --show-diff-on-failure --verbose
