name: Release OSP Director Operator

on:
  release:
    types:
      - released
      - prereleased

env:
  imageregistry: 'quay.io'
  imagenamespace: ${{ secrets.IMAGENAMESPACE || secrets.QUAY_USERNAME }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Tag osp-director-operator image
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ env.imagenamespace }}/osp-director-operator
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: ${{ env.imageregistry }}
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}

    - name: Tag rhel-downloader image
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ env.imagenamespace }}/rhel-downloader
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: ${{ env.imageregistry }}
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}

    - name: Tag agent image
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ env.imagenamespace }}/osp-director-operator-agent
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: ${{ env.imageregistry }}
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}

    - name: Tag osp-director-operator-bundle image
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ env.imagenamespace }}/osp-director-operator-bundle
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: ${{ env.imageregistry }}
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}

    - name: Tag osp-director-operator-index image
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ env.imagenamespace }}/osp-director-operator-index
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: ${{ env.imageregistry }}
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}
